# Generated by Django 4.1.1 on 2023-03-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensor_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="locId",
            field=models.CharField(
                default="LOC20928", editable=False, max_length=50, unique=True
            ),
        ),
    ]
