# Generated by Django 4.1.1 on 2023-04-20 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sensor_app", "0003_alter_location_locid"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="userName",
            field=models.CharField(default="Default User", max_length=100),
        ),
        migrations.AlterField(
            model_name="location",
            name="locId",
            field=models.CharField(
                default="LOC28468", editable=False, max_length=50, unique=True
            ),
        ),
        migrations.CreateModel(
            name="UserLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
