# Generated by Django 4.1.1 on 2023-04-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensor_app", "0005_userlogs_isseen_alter_location_locid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="locId",
            field=models.CharField(
                default="LOC69044", editable=False, max_length=50, unique=True
            ),
        ),
    ]
