# Generated by Django 4.1.1 on 2023-04-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensor_app", "0008_alter_location_locid"),
    ]

    operations = [
        migrations.RemoveField(model_name="userlogs", name="user",),
        migrations.AddField(
            model_name="userlogs",
            name="userName",
            field=models.CharField(default="Default User", max_length=100),
        ),
        migrations.AlterField(
            model_name="location",
            name="locId",
            field=models.CharField(
                default="LOC19170", editable=False, max_length=50, unique=True
            ),
        ),
    ]
