# Generated by Django 4.1.1 on 2023-05-10 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sensor_app', '0009_remove_userlogs_user_userlogs_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='locId',
            field=models.CharField(default='LOC30653', editable=False, max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.CharField(default='0', max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
