# Generated by Django 4.1.1 on 2023-05-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_app', '0010_alter_location_locid_userinteraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='locId',
            field=models.CharField(default='LOC30827', editable=False, max_length=50, unique=True),
        ),
    ]
